name: Run Python Script

on:
  workflow_dispatch:   # تشغيل يدوي من صفحة Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: python add_flags.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: flagged-channels
          path: Twin-English-Nemrawy-3-2026-flags.txt
