name: Run Python Script

on:
  workflow_dispatch:   # يسمح بتشغيل الـ Workflow يدويًا من صفحة Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # أحدث نسخة

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: python add_flags.py

      - name: Upload result
        uses: actions/upload-artifact@v4   # الإصدار الجديد
        with:
          name: flagged-channels
          path: Twin-flags.txt
